name: CICD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

jobs:
  ci:
    permissions: write-all
    name: Calidad de codigo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Commit
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit install
          pre-commit run --all-files

  cd:
    needs: [ci]
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile
        run: |
          pip install -r src/pipelines/requirements.txt
          python -B src/pipelines/iris_pipeline.py

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          project_id: 'mlops-first-proyect'
          workload_identity_provider: 'projects/405581335268/locations/global/workloadIdentityPools/1234gus/providers/gustavito'
          service_account: 'mlops-proyect-testing@mlops-first-proyect.iam.gserviceaccount.com'

      - name: Register
        run: |
          curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F tags=latest \
          -F content=@pipeline.yaml \
          https://us-west2-kfp.pkg.dev/mlops-first-proyect/mlops
