name: CICD

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

jobs:
  ci:
    permissions: write-all
    name: Calidad de codigo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pre-Commit
        run: |
          pip install pre-commit
          pre-commit --version
          pre-commit install
          pre-commit run --all-files

  cd:
    needs: [ci]
    name: Deploy
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Compile
        run: |
          python -m pip install wheel
          pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -r src/pipelines/requirements.txt --use-deprecated=legacy-resolver
          python -B src/pipelines/iris_pipeline.py

      - name: 'GCP Auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'mlops-first-proyect'
          workload_identity_provider: 'projects/405581335268/locations/global/workloadIdentityPools/github-mlops/providers/github-provider-provider'
          service_account: 'mlops-iris@mlops-first-proyect.iam.gserviceaccount.com'

      - name: Register
        run: |
          curl -X POST \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -F tags=latest \
          -F content=@pipeline.yaml \
          https://us-central1-kfp.pkg.dev/mlops-first-proyect/mlops
